### PR TITLE
Code format

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
- [x] wait for merge of https://github.com/fntsoftware/jdbc-check/pull/1 - then rebase and un-draft this PR

**Review by andreas-stegmaier-fnt — APPROVED** [review]
Maybe squash the commits before merging

**Comment by ghost** [comment]
> Maybe squash the commits before merging

We can just do a Squash merge when we merge this PR. I did 2 commits by design, one which adds the code formatter and one which applies the new code format. Makes it much more easy to review this PR imo. 😄

**Comment by ghost** [comment]
- [x] merge using squash merge

**Review by andreas-volz-fnt — APPROVED** [review]

**Pull request merged**
